In [1]:
import json                                                         # this module is used to read json files
import os 
from PIL import Image
import matplotlib.pyplot as plt 
path = "D:/test 9/photo/"
dirs = os.listdir(path)

for item in dirs:
    if os.path.isfile(path+item):
        img = Image.open(path+item)
        f, e = os.path.splitext(path+item)
        flip_img = img.transpose(Image.FLIP_LEFT_RIGHT)
        flip_img.save(f+'_flip'+'.bmp')

In [14]:
# g=file.split(".")# for each file in the folder
txt_outfile = open("D:/test 9/70_image_4029_flip.txt",'r') #creating labelimg/YOLO files of same name
txt_outfile.read()
txt_outfile.seek(0)
txt_outfile.close()

In [2]:
import pandas as pd
dk = pd.read_table("D:/test 9/70_image_4030_flip.txt",delimiter=" ")

print(dk.index)

RangeIndex(start=0, stop=17, step=1)


In [3]:
df = pd.read_fwf("D:/test 9/70_image_4030_flip.txt")
  
# display DataFrame
print(df)
df = tabulate(df)
print(df)

    0  0.922172  0.280423  0.063830  0.222222
0   0  0.829787  0.296296  0.064950  0.222222
1   0  0.736842  0.309524  0.064950  0.238095
2   0  0.592945  0.301587  0.066069  0.232804
3   0  0.497200  0.314815  0.067189  0.238095
4   0  0.402576  0.312169  0.068309  0.232804
5   0  0.259798  0.317460  0.067189  0.232804
6   0  0.167413  0.312169  0.063830  0.232804
7   0  0.080067  0.320106  0.061590  0.227513
8   0  0.921613  0.711640  0.060470  0.227513
9   0  0.828108  0.722222  0.061590  0.238095
10  0  0.735722  0.701058  0.064950  0.216931
11  0  0.591265  0.738095  0.067189  0.227513
12  0  0.494401  0.735450  0.066069  0.232804
13  0  0.400336  0.740741  0.066069  0.222222
14  0  0.262038  0.727513  0.062710  0.259259
15  0  0.171333  0.735450  0.064950  0.232804
16  0  0.082307  0.730159  0.063830  0.222222


NameError: name 'tabulate' is not defined

In [5]:
import pandas as pd
data = pd.read_csv('D:/test 9/70_image_4029_flip.txt', sep=" ", header=None)
data[1] = 1- data[1]

for i in (len(data))
print(data[1][0])

# txt_outfile = open("D:/test 9/70_image_4030_flip.txt",'r+') #creating labelimg/YOLO files of same name
# txt_outfile.write(str(data))
# txt_outfile.seek(0)
# txt_outfile.close()

SyntaxError: invalid syntax (4165518314.py, line 5)

In [6]:
import numpy as np
f=open('D:/test 9/70_image_4029_flip.txt',"r+")
lines=f.readlines()
for x in lines:
    result.append(x.split(' ')[1])
print(result)
f.close()


NameError: name 'result' is not defined

In [7]:
import numpy as np
a = np.loadtxt("D:/test 9/70_image_4030_flip.txt")[:,1::]
b= np.loadtxt("D:/test 9/70_image_4030_flip.txt")[:, 1]
r,c=np.shape(a)
# for i in range(len(b)):
#     b[i]=1-b[i]
i=0
for ele in a[:,0]:
    ele=1-ele
    a[i,0]=ele
    i+=1
print(a)

# for i in range (len(a[:,0])):
#     d[i,0] = int(a[i,0])
print(a[:,0])
b= 0+a
np.savetxt('D:/test 9/70_image_4032_flip.txt',a,fmt='%-7.6f')
# txt_outfile = open("D:/test 9/70_image_4032_flip.txt",'r+') #creating labelimg/YOLO files of same name
# txt_outfile.write(""+" "+  '\n')
# txt_outfile.seek(0)
# txt_outfile.close()

[[0.077828 0.280423 0.06383  0.222222]
 [0.170213 0.296296 0.06495  0.222222]
 [0.263158 0.309524 0.06495  0.238095]
 [0.407055 0.301587 0.066069 0.232804]
 [0.5028   0.314815 0.067189 0.238095]
 [0.597424 0.312169 0.068309 0.232804]
 [0.740202 0.31746  0.067189 0.232804]
 [0.832587 0.312169 0.06383  0.232804]
 [0.919933 0.320106 0.06159  0.227513]
 [0.078387 0.71164  0.06047  0.227513]
 [0.171892 0.722222 0.06159  0.238095]
 [0.264278 0.701058 0.06495  0.216931]
 [0.408735 0.738095 0.067189 0.227513]
 [0.505599 0.73545  0.066069 0.232804]
 [0.599664 0.740741 0.066069 0.222222]
 [0.737962 0.727513 0.06271  0.259259]
 [0.828667 0.73545  0.06495  0.232804]
 [0.917693 0.730159 0.06383  0.222222]]
[0.077828 0.170213 0.263158 0.407055 0.5028   0.597424 0.740202 0.832587
 0.919933 0.078387 0.171892 0.264278 0.408735 0.505599 0.599664 0.737962
 0.828667 0.917693]


In [8]:
f = open ( 'D:/test 9/70_image_4029_flip.txt' , 'r+')
l = [ map(str,line.split('\t')) for line in f ]

In [9]:
print(f)

<_io.TextIOWrapper name='D:/test 9/70_image_4029_flip.txt' mode='r+' encoding='cp1252'>


In [10]:
f = open ( 'D:/test 9/70_image_4029_flip.txt' , 'r+')

rows = []
for line in f:
    # Split on any whitespace (including tab characters)
    row = line.split()
    # Convert strings to numeric values:


    # Append to our list of lists:
    rows.append(row)



In [11]:
from tabulate import tabulate
# assign data
mydata = [
    ["Nikhil", "Delhi"],
    ["Ravi", "Kanpur"],
    ["Manish", "Ahmedabad"],
      ["Prince", "Bangalore"]
]
 
# create header
head = ["Name", "City"]
 
# display table
x = tabulate(a, tablefmt="plain")

In [12]:
with open('table.txt', 'w') as f:
    f.write(x)

In [72]:
import numpy as np
from tabulate import tabulate
a = np.loadtxt("D:/test 9/70_image_4030_flip.txt")

i=0
for ele in a[:,1]:
    ele=1-ele
    a[i,1]=ele
    i+=1
print(a)
a =  tabulate(a,tablefmt="plain",floatfmt=(".0f", ".6f",".6f",".6f",".6f"),colalign=("left"))
print(a)

with open('D:/test 9/70_image_4030_flip.txt', 'w') as f:
    f.write(a.replace("  "," "))




[[0.       0.922172 0.280423 0.06383  0.222222]
 [0.       0.829787 0.296296 0.06495  0.222222]
 [0.       0.736842 0.309524 0.06495  0.238095]
 [0.       0.592945 0.301587 0.066069 0.232804]
 [0.       0.4972   0.314815 0.067189 0.238095]
 [0.       0.402576 0.312169 0.068309 0.232804]
 [0.       0.259798 0.31746  0.067189 0.232804]
 [0.       0.167413 0.312169 0.06383  0.232804]
 [0.       0.080067 0.320106 0.06159  0.227513]
 [0.       0.921613 0.71164  0.06047  0.227513]
 [0.       0.828108 0.722222 0.06159  0.238095]
 [0.       0.735722 0.701058 0.06495  0.216931]
 [0.       0.591265 0.738095 0.067189 0.227513]
 [0.       0.494401 0.73545  0.066069 0.232804]
 [0.       0.400336 0.740741 0.066069 0.222222]
 [0.       0.262038 0.727513 0.06271  0.259259]
 [0.       0.171333 0.73545  0.06495  0.232804]
 [0.       0.082307 0.730159 0.06383  0.222222]]
0  0.922172  0.280423  0.063830  0.222222
0  0.829787  0.296296  0.064950  0.222222
0  0.736842  0.309524  0.064950  0.238095
0  0.5929

In [14]:
# r,c=a.shape
# print(r,c)
# i=0
# j=0
# print(len(a))
# for i in len(a):
#     print(" ")
#     for j in i:
#         print(j,end=" ")
        

In [65]:
for index,i in enumerate(a):
    if(i==" " and i==" "):
        a.replace(" ","")
        print(index)
print(a)

1
2
11
12
21
22
31
32
43
44
53
54
63
64
73
74
85
86
95
96
105
106
115
116
127
128
137
138
147
148
157
158
169
170
179
180
189
190
199
200
211
212
221
222
231
232
241
242
253
254
263
264
273
274
283
284
295
296
305
306
315
316
325
326
337
338
347
348
357
358
367
368
379
380
389
390
399
400
409
410
421
422
431
432
441
442
451
452
463
464
473
474
483
484
493
494
505
506
515
516
525
526
535
536
547
548
557
558
567
568
577
578
589
590
599
600
609
610
619
620
631
632
641
642
651
652
661
662
673
674
683
684
693
694
703
704
715
716
725
726
735
736
745
746
0  0.922172  0.280423  0.063830  0.222222
0  0.829787  0.296296  0.064950  0.222222
0  0.736842  0.309524  0.064950  0.238095
0  0.592945  0.301587  0.066069  0.232804
0  0.497200  0.314815  0.067189  0.238095
0  0.402576  0.312169  0.068309  0.232804
0  0.259798  0.317460  0.067189  0.232804
0  0.167413  0.312169  0.063830  0.232804
0  0.080067  0.320106  0.061590  0.227513
0  0.921613  0.711640  0.060470  0.227513
0  0.828108  0.722222  0.0

In [52]:
print(a)

0  0.922172  0.280423  0.063830  0.222222
0  0.829787  0.296296  0.064950  0.222222
0  0.736842  0.309524  0.064950  0.238095
0  0.592945  0.301587  0.066069  0.232804
0  0.497200  0.314815  0.067189  0.238095
0  0.402576  0.312169  0.068309  0.232804
0  0.259798  0.317460  0.067189  0.232804
0  0.167413  0.312169  0.063830  0.232804
0  0.080067  0.320106  0.061590  0.227513
0  0.921613  0.711640  0.060470  0.227513
0  0.828108  0.722222  0.061590  0.238095
0  0.735722  0.701058  0.064950  0.216931
0  0.591265  0.738095  0.067189  0.227513
0  0.494401  0.735450  0.066069  0.232804
0  0.400336  0.740741  0.066069  0.222222
0  0.262038  0.727513  0.062710  0.259259
0  0.171333  0.735450  0.064950  0.232804
0  0.082307  0.730159  0.063830  0.222222


In [66]:
a.replace(" ","")


'00.9221720.2804230.0638300.222222\n00.8297870.2962960.0649500.222222\n00.7368420.3095240.0649500.238095\n00.5929450.3015870.0660690.232804\n00.4972000.3148150.0671890.238095\n00.4025760.3121690.0683090.232804\n00.2597980.3174600.0671890.232804\n00.1674130.3121690.0638300.232804\n00.0800670.3201060.0615900.227513\n00.9216130.7116400.0604700.227513\n00.8281080.7222220.0615900.238095\n00.7357220.7010580.0649500.216931\n00.5912650.7380950.0671890.227513\n00.4944010.7354500.0660690.232804\n00.4003360.7407410.0660690.222222\n00.2620380.7275130.0627100.259259\n00.1713330.7354500.0649500.232804\n00.0823070.7301590.0638300.222222'

In [61]:
print(a)

0  0.922172  0.280423  0.063830  0.222222
0  0.829787  0.296296  0.064950  0.222222
0  0.736842  0.309524  0.064950  0.238095
0  0.592945  0.301587  0.066069  0.232804
0  0.497200  0.314815  0.067189  0.238095
0  0.402576  0.312169  0.068309  0.232804
0  0.259798  0.317460  0.067189  0.232804
0  0.167413  0.312169  0.063830  0.232804
0  0.080067  0.320106  0.061590  0.227513
0  0.921613  0.711640  0.060470  0.227513
0  0.828108  0.722222  0.061590  0.238095
0  0.735722  0.701058  0.064950  0.216931
0  0.591265  0.738095  0.067189  0.227513
0  0.494401  0.735450  0.066069  0.232804
0  0.400336  0.740741  0.066069  0.222222
0  0.262038  0.727513  0.062710  0.259259
0  0.171333  0.735450  0.064950  0.232804
0  0.082307  0.730159  0.063830  0.222222


# Final labelimg flip

In [ ]:
import numpy as np
from tabulate import tabulate
a = np.loadtxt("D:/test 9/70_image_4030_flip.txt")

i=0
for ele in a[:,1]:
    ele=1-ele
    a[i,1]=ele
    i+=1
print(a)
a =  tabulate(a,tablefmt="plain",floatfmt=(".0f", ".6f",".6f",".6f",".6f"),colalign=("left"))
print(a)

with open('D:/test 9/70_image_4030_flip.txt', 'w') as f:
    f.write(a.replace("  "," "))


